/*
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package org.xtext.vaadin.example.geo.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.vaadin.example.geo.ui.internal.GeoActivator;

public class GeoDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GeoActivator.getInstance().getInjector("org.xtext.vaadin.example.geo.GeoDsl");
	}

}
