/*
 * generated by Xtext 2.19.0
 */
package org.xtext.vaadin.example.geo


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GeoDslStandaloneSetup extends GeoDslStandaloneSetupGenerated {

	def static void doSetup() {
		new GeoDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
