/**
 * generated by Xtext 2.19.0
 */
package org.xtext.vaadin.example.geo.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.vaadin.example.geo.GeoDslRuntimeModule;
import org.xtext.vaadin.example.geo.GeoDslStandaloneSetup;
import org.xtext.vaadin.example.geo.ide.GeoDslIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class GeoDslIdeSetup extends GeoDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    GeoDslRuntimeModule _geoDslRuntimeModule = new GeoDslRuntimeModule();
    GeoDslIdeModule _geoDslIdeModule = new GeoDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_geoDslRuntimeModule, _geoDslIdeModule));
  }
}
