/**
 * generated by Xtext 2.19.0
 */
package org.xtext.vaadin.example.geo.ide;

import org.xtext.vaadin.example.geo.ide.AbstractGeoDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GeoDslIdeModule extends AbstractGeoDslIdeModule {
}
