/*
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package org.xtext.vaadin.example.geo.ui.editor;

import org.eclipse.xtext.xbase.ui.editor.XbaseEditor;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass.
 */
public class GeoDslEditor extends XbaseEditor {
}
