/**
 * generated by Xtext 2.19.0
 */
package org.xtext.vaadin.example.geo;

import org.xtext.vaadin.example.geo.GeoDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GeoDslStandaloneSetup extends GeoDslStandaloneSetupGenerated {
  public static void doSetup() {
    new GeoDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
