/**
 * generated by Xtext 2.19.0
 */
package org.xtext.vaadin.example.geo.ui.quickfix;

import org.eclipse.xtext.xbase.annotations.ui.quickfix.XbaseWithAnnotationsQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class GeoDslQuickfixProvider extends XbaseWithAnnotationsQuickfixProvider {
}
