/**
 * generated by Xtext 2.19.0
 */
package org.xtext.vaadin.example.geo.scoping;

import org.xtext.vaadin.example.geo.scoping.AbstractGeoDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class GeoDslScopeProvider extends AbstractGeoDslScopeProvider {
}
