/*
 * generated by Xtext 2.19.0
 */
package org.xtext.vaadin.example.geo.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import org.eclipse.xtext.builder.IXtextBuilderParticipant

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class GeoDslUiModule extends AbstractGeoDslUiModule {
	override Class<? extends IXtextBuilderParticipant> bindIXtextBuilderParticipant() {
		return GeoCustomBuilderParticipant;
	}
}
