/*
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package org.xtext.vaadin.example.geo.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.vaadin.example.geo.ui.internal.GeoActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GeoDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(GeoActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		GeoActivator activator = GeoActivator.getInstance();
		return activator != null ? activator.getInjector(GeoActivator.ORG_XTEXT_VAADIN_EXAMPLE_GEO_GEODSL) : null;
	}

}
